import Head from "next/head";
import Header from "../components/Header.js";
import Banner from "../components/Banner.js";
import SmallCard from "../components/SmallCard.js";
import MediumCard from "../components/MediumCard.js";
import LargeCard from "../components/LargeCard.js";
import Footer from "../components/Footer.js";

export default function Home({ exploreData, cardsData }) {
  return (
    <div className="">
      <Head>
        <title>PAPA Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />

      <main className="max-w-6xl mx-auto px-8 sm:px-16 2xl:max-w-7xl">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold">Explore Nearby</h2>

          {/* cards data through server side rendering */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map((item) => (
              <SmallCard
                key={item.img}
                img={item.img}
                location={item.location}
                distance={item.distance}
              />
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
            {cardsData?.map((item) => (
              <MediumCard key={item.img} img={item.img} title={item.title} />
            ))}
          </div>
        </section>

        <LargeCard
          img="https://links.papareact.com/4cj"
          title="The Greatest Outdoors"
          description="Wishlists curated by Airbnb"
          buttonText="Get Inspired"
        />
      </main>

      <Footer />
    </div>
  );
}

export const getStaticProps = async () => {
  const exploreData = await fetch("https://www.jsonkeeper.com/b/4G1G").then(
    (res) => res.json()
  );
  const cardsData = await fetch("https://www.jsonkeeper.com/b/VHHT").then(
    (res) => res.json()
  );
  return {
    props: {
      exploreData,
      cardsData,
    },
  };
};
